<a href="https://colab.research.google.com/github/skywalker0803r/mxnet_course/blob/master/mxnet_actor_critic_model_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import warnings;warnings.simplefilter('ignore')
import random
import numpy as np
from time import sleep
import mxnet as mx
import mxnet.gluon as gluon
from mxnet import nd, autograd
import gym

# define model

In [0]:
class Net(gluon.Block):
  def __init__(self, actions_count):
    super(Net, self).__init__()
    with self.name_scope():
      self.dense1 = gluon.nn.Dense(128, activation='relu')
      self.dense2 = gluon.nn.Dense(128, activation='relu')
      self.action_pred = gluon.nn.Dense(actions_count, in_units=128)
      self.value_pred = gluon.nn.Dense(1, in_units=128)
  
  def forward(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    probs = self.action_pred(x)
    values = self.value_pred(x)
    return nd.softmax(probs), values

# create env

In [3]:
env = gym.make("CartPole-v1")
action_dim = env.action_space.n
state_dim = env.observation_space.shape[0]
print(state_dim,action_dim)

4 2


# forward test

In [4]:
state = env.reset()
state = nd.array([state])
print(state)


[[-0.00875129 -0.03046686 -0.00029008  0.0425537 ]]
<NDArray 1x4 @cpu(0)>


In [5]:
model = Net(action_dim)
model.collect_params().initialize(mx.init.Xavier())
print(model(state))

(
[[0.5041903  0.49580967]]
<NDArray 1x2 @cpu(0)>, 
[[-0.00319634]]
<NDArray 1x1 @cpu(0)>)


# copy params test

In [6]:
model_1 = Net(action_dim)
model_1.collect_params().initialize(mx.init.Xavier())

model_2 = Net(action_dim)
model_2.collect_params().initialize(mx.init.Xavier())

print(model_1(state))
print(model_2(state))

model_1.save_parameters('temp')
model_2.load_parameters('temp')

print(model_1(state))
print(model_2(state))

(
[[0.5009675  0.49903244]]
<NDArray 1x2 @cpu(0)>, 
[[-0.00323182]]
<NDArray 1x1 @cpu(0)>)
(
[[0.5034521  0.49654788]]
<NDArray 1x2 @cpu(0)>, 
[[-0.00532455]]
<NDArray 1x1 @cpu(0)>)
(
[[0.5009675  0.49903244]]
<NDArray 1x2 @cpu(0)>, 
[[-0.00323182]]
<NDArray 1x1 @cpu(0)>)
(
[[0.5009675  0.49903244]]
<NDArray 1x2 @cpu(0)>, 
[[-0.00323182]]
<NDArray 1x1 @cpu(0)>)
