<a href="https://colab.research.google.com/github/skywalker0803r/mxnet_course/blob/master/mxnet_build_policy_value_net_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#!pip install mxnet
import warnings;warnings.simplefilter('ignore')
import random
import numpy as np
from time import sleep
import mxnet as mx
from mxnet import init
import mxnet.gluon as gluon
from mxnet.gluon import nn
from mxnet import nd, autograd

# define policy and value net

In [0]:
def get_policy_net(action_dim):
  net = nn.HybridSequential()
  net.add(nn.Dense(128,activation='relu'))
  net.add(nn.Dense(128,activation='relu'))
  net.add(nn.Dense(action_dim))
  net.initialize(init.Xavier())
  net.hybridize()
  return net

In [0]:
def get_value_net():
  net = nn.HybridSequential()
  net.add(nn.Dense(128, activation='relu'))
  net.add(nn.Dense(128, activation='relu'))
  net.add(nn.Dense(1))
  net.initialize(init.Xavier())
  net.hybridize()
  return net

# test policy and value net

In [0]:
state_dim = 4
action_dim = 2
batch_size = 3

In [5]:
state = nd.random.uniform(shape=(batch_size,state_dim))
print('state:',state)

state: 
[[0.5488135  0.5928446  0.71518934 0.84426576]
 [0.60276335 0.8579456  0.5448832  0.8472517 ]
 [0.4236548  0.6235637  0.6458941  0.3843817 ]]
<NDArray 3x4 @cpu(0)>


In [6]:
policy_net = get_policy_net(action_dim)
probs= policy_net(state)
print('probs',probs)

probs 
[[ 0.01244259 -0.10175639]
 [ 0.02120219 -0.11203857]
 [ 0.03049981 -0.08028838]]
<NDArray 3x2 @cpu(0)>


In [7]:
value_net = get_value_net()
values= value_net(state)
print('values',values)

values 
[[-0.06922802]
 [-0.04454572]
 [-0.04818239]]
<NDArray 3x1 @cpu(0)>


# export model

In [8]:
policy_net.export("test_policy_net")
value_net.export("test_value_net")
print('export done!')

export done!


# load model

In [9]:
deserialized_policy_net = gluon.nn.SymbolBlock.imports("test_policy_net-symbol.json",['data'],"test_policy_net-0000.params")
probs= deserialized_policy_net(state)
print('probs',probs)

probs 
[[ 0.01244259 -0.10175639]
 [ 0.02120219 -0.11203857]
 [ 0.03049981 -0.08028838]]
<NDArray 3x2 @cpu(0)>


In [10]:
deserialized_value_net = gluon.nn.SymbolBlock.imports("test_value_net-symbol.json",['data'],"test_value_net-0000.params")
values = deserialized_value_net(state)
print('values',values)

values 
[[-0.06922802]
 [-0.04454572]
 [-0.04818239]]
<NDArray 3x1 @cpu(0)>
